import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import Banner from '../components/banner'
import Card from '../components/Card'
import coffeeStoresData from "../data/coffee-stores.json"
import Container from '../components/Container'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps(context){

  return{
    props: {
      coffeeStores: coffeeStoresData,
    },
  };
}

export default function Home(props) {
  
  function handleOnBannerBtn() {
    console.log("hi");
  }
  return (
    <>
      <Head>
        <title>Coffee Discourier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <Container>
    <Banner  buttonText='View stores nearby' 
    handleOnClick={handleOnBannerBtn}/>
    <Image 
    src="/static/hero-image.png" 
    width={700} 
    height={400}
    alt='/'
    className="absolute top-[62px] pt-[60px] md:top-10 z-1 md:right-[20%]"
    />
    {props.coffeeStores.length > 0 &&  (  <> 
    <h2 className='  mt-4 pt-[180px] text-[#fff] text-4xl font-bold'>Toronto stores</h2>
    <div className='grid md:grid-cols-2 lg:grid-cols-3 gap-2  text-[#4B0082]'>
      {props.coffeeStores.map((coffeeStore) => (
          <Card key={coffeeStore.id}
          name={coffeeStore.name}
          imgUrl={coffeeStore.imgUrl}
          href={`/coffee-store/${coffeeStore.id}`}
          />
      ))}
      
     
    
    </div>
    </>
    )
    

}
</Container>

        
           
          
      </main>
    </>
  )
}
